CREATE TABLE "shortened_links" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "shortened_links_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"user_id" varchar(255) NOT NULL,
	"short_code" varchar(32) NOT NULL,
	"url" text NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE UNIQUE INDEX "shortened_links_short_code_uidx" ON "shortened_links" USING btree ("short_code");--> statement-breakpoint
CREATE INDEX "shortened_links_user_id_idx" ON "shortened_links" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX "shortened_links_user_created_at_idx" ON "shortened_links" USING btree ("user_id","created_at");